'use client'

import { forwardRef } from 'react'
import { Sparkles, Skull, AlertTriangle, Fingerprint } from 'lucide-react'

interface RoastCardProps {
  score: number
  roast: string
  cliches: string[]
  oneLiner: string
  animal: string
  name?: string
}

const RoastCard = forwardRef<HTMLDivElement, RoastCardProps>(({ score, cliches, oneLiner, animal }, ref) => {

  // Determine card style based on score
  const getTheme = (score: number) => {
    if (score <= 3) return {
      bg: "bg-[#1a1a1a]",
      accent: "text-red-500",
      border: "border-red-500/50",
      stamp: "border-red-600 text-red-600",
      label: "UNEMPLOYABLE"
    }
    if (score <= 6) return {
      bg: "bg-[#1a1a1a]",
      accent: "text-orange-500",
      border: "border-orange-500/50",
      stamp: "border-orange-600 text-orange-600",
      label: "MID CARD"
    }
    return {
      bg: "bg-[#1a1a1a]",
      accent: "text-green-500",
      border: "border-green-500/50",
      stamp: "border-green-600 text-green-600",
      label: "SURVIVOR"
    }
  }

  const theme = getTheme(score)

  return (
    <div
      ref={ref}
      className={`relative w-full max-w-md aspect-[3/4] ${theme.bg} text-white p-6 shadow-2xl flex flex-col justify-between overflow-hidden font-mono border-8 ${theme.border}`}
    >
      {/* Background Image - User Provided */}
      <div
        className="absolute inset-0 pointer-events-none bg-cover bg-center opacity-20 mix-blend-overlay"
        style={{ backgroundImage: "url('/money-bg.png')" }}
      ></div>

      {/* Paper Texture Overlay */}
      <div className="absolute inset-0 opacity-10 pointer-events-none bg-[url('https://www.transparenttextures.com/patterns/cardboard-flat.png')]"></div>

      {/* "WANTED" Header Style */}
      <div className="relative z-10 text-center border-b-4 border-white pb-4 mb-4">
        <div className="flex justify-between items-center mb-2 px-2">
            <span className="text-xs text-gray-400">CASE #2024-{Math.floor(Math.random() * 9999)}</span>
            <span className="text-xs text-gray-400">BLOOM AI DEPT.</span>
        </div>
        <h1 className={`text-5xl font-black tracking-tighter ${theme.accent} uppercase`} style={{ textShadow: '2px 2px 0px rgba(0,0,0,1)' }}>
          {theme.label}
        </h1>
      </div>

      {/* Main Stats / Mugshot Area */}
      <div className="relative z-10 flex-1 flex flex-col gap-4">

        {/* The One Liner (Quote) */}
        <div className="bg-white/5 border border-white/10 p-4 relative">
             <span className="absolute -top-3 -left-2 text-4xl text-white/20">"</span>
             <p className="text-xl font-bold text-center leading-tight uppercase italic font-serif">
               {oneLiner}
             </p>
             <span className="absolute -bottom-6 -right-2 text-4xl text-white/20">"</span>
        </div>

        {/* Info Grid */}
        <div className="grid grid-cols-2 gap-4 mt-4">
            <div className="border-2 border-dashed border-white/20 p-3 flex flex-col items-center justify-center">
                <span className="text-xs uppercase text-gray-500 mb-1">Spirit Animal</span>
                <span className={`font-bold text-lg ${theme.accent}`}>{animal}</span>
            </div>
            <div className="border-2 border-dashed border-white/20 p-3 flex flex-col items-center justify-center">
                 <span className="text-xs uppercase text-gray-500 mb-1">Toxicity Level</span>
                 <div className="flex gap-1">
                    {[...Array(5)].map((_, i) => (
                        <Skull key={i} className={`w-4 h-4 ${i < (10 - score) / 2 ? 'text-red-500' : 'text-gray-700'}`} />
                    ))}
                 </div>
            </div>
        </div>

        {/* Cliches List */}
        <div className="mt-2">
            <p className="text-xs uppercase bg-white text-black inline-block px-1 font-bold mb-2">Evidence Found:</p>
            <ul className="text-sm space-y-1 text-gray-300">
                {cliches.slice(0, 3).map((c, i) => (
                    <li key={i} className="flex items-center gap-2">
                        <AlertTriangle className="w-3 h-3 text-yellow-500" />
                        {c}
                    </li>
                ))}
            </ul>
        </div>
      </div>

      {/* Footer / Stamp */}
      <div className="relative z-10 mt-6 flex justify-between items-end border-t-4 border-white pt-4">
         <div className="flex flex-col">
             <span className="text-[10px] text-gray-500">GENERATED BY</span>
             <span className="font-bold text-lg tracking-widest">BLOOM.AI</span>
         </div>

         {/* Stamped Score */}
         <div className={`border-4 ${theme.stamp} p-2 rounded rotate-[-12deg] opacity-90 mask-image-grunge`}>
             <span className={`text-4xl font-black ${theme.stamp}`}>
                 {score}/10
             </span>
         </div>

         <div className="opacity-30">
             <Fingerprint className="w-12 h-12" />
         </div>
      </div>

    </div>
  )
})

RoastCard.displayName = "RoastCard"

export default RoastCard
